### ISSUE TITLE
Modifying ibc/config.ini variables without rebuilding image?

### ISSUE THREAD

**Issue by ttamg** [UnusualAlpha/ib-gateway-docker#1]
Great you are maintaining this.  Thanks!

I want to set `ReadOnlyAPI=no` for more configuration in `/config/ibc/config.ini`.  I can rebuild the image myself of course but I was wondering if there's a way of injecting this or if we might create environment variables for some of the config options that people might want to change.

I tried mounting a volume on `/root/ibc` but there are other files in that config folder that I need to then pull across too.

I can find a way around it and will build my own container, but just wanted to raise this in case you already have a smarter idea.  Thanks

**Comment by efernandesng** [comment]
Hi @ttamg!

I think a way to solve that, is maybe we should use an env var. I'll create a new release with that feature in the following days.

**Comment by ttamg** [comment]
Excellent.  Thanks.

**Comment by efernandesng** [comment]
Hi @ttamg sorry for the delay.

Now you should be able to use the new `READ_ONLY_API` environment variable to set the IBC `ReadOnlyApi` value.

Available on the [tags](https://github.com/UnusualAlpha/ib-gateway-docker/pkgs/container/ib-gateway/): `latest`, `10.16.1n`, `stable` and `10.12.2p`
