### ISSUE TITLE
out of memory core dumped

### ISSUE THREAD

**Issue by yokotsumo** [UnusualAlpha/ib-gateway-docker#108]
**Describe the bug**
setup 9/17: RUN ./ibgateway-10.22.1m-standalone-linux-x64.sh -q -dir /root/Jts/ibgateway/10.22.1m
generates core dumped due to out of memory

**To Reproduce**
just set variables and launch:
docker-compose up --build

**Expected behavior**
Creation and launch of ibgateway docker service

**Container logs**
docker-compose up --build
Building ib-gateway
[+] Building 336.3s (16/27)                                      docker:default
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 2.62kB                                     0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04            0.9s
 => [setup  1/17] FROM docker.io/library/ubuntu:22.04@sha256:aabed3296a3d  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 1.04kB                                        0.0s
 => CACHED [setup  2/17] RUN apt-get update -y                             0.0s
 => CACHED [setup  3/17] RUN apt-get install --no-install-recommends --ye  0.0s
 => CACHED [setup  4/17] WORKDIR /tmp/setup                                0.0s
 => CACHED [stage-1 2/7] WORKDIR /root                                     0.0s
 => CACHED [stage-1 3/7] RUN apt-get update -y                             0.0s
 => [stage-1 4/7] RUN apt-get install --no-install-recommends --yes   g  196.6s
 => [setup  5/17] RUN curl -sSL https://github.com/UnusualAlpha/ib-gate  327.7s
 => [setup  6/17] RUN curl -sSL https://github.com/UnusualAlpha/ib-gatewa  1.9s 
 => [setup  7/17] RUN sha256sum --check ./ibgateway-10.22.1m-standalone-l  1.0s 
 => [setup  8/17] RUN chmod a+x ./ibgateway-10.22.1m-standalone-linux-x64  0.5s 
 => ERROR [setup  9/17] RUN ./ibgateway-10.22.1m-standalone-linux-x64.sh   4.1s 
------                                                                          
 > [setup  9/17] RUN ./ibgateway-10.22.1m-standalone-linux-x64.sh -q -dir /root/Jts/ibgateway/10.22.1m:                                                         
0.906 Unpacking JRE ...
3.509 Starting Installer ...
3.599 library initialization failed - unable to allocate file descriptor table - out of memoryAborted (core dumped)
------
Dockerfile:33
--------------------
  31 |     RUN sha256sum --check ./ibgateway-${IB_GATEWAY_VERSION}-standalone-linux-x64.sh.sha256
  32 |     RUN chmod a+x ./ibgateway-${IB_GATEWAY_VERSION}-standalone-linux-x64.sh
  33 | >>> RUN ./ibgateway-${IB_GATEWAY_VERSION}-standalone-linux-x64.sh -q -dir /root/Jts/ibgateway/${IB_GATEWAY_VERSION}
  34 |     COPY ./config/ibgateway/jts.ini /root/Jts/jts.ini
  35 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c ./ibgateway-${IB_GATEWAY_VERSION}-standalone-linux-x64.sh -q -dir /root/Jts/ibgateway/${IB_GATEWAY_VERSION}" did not complete successfully: exit code: 134
ERROR: Service 'ib-gateway' failed to build : Build failed

**Versions (please complete the following information):**
 - OS: Fedora 38, Linux 6.5.5-200.fc38.x86_64
 - Docker version: Docker Engine - Community
 - Image Tag (`docker --version`): Docker version 24.0.6, build ed223bc
 - Image Digest (`docker images --digests`): image not created

**Additional context**
Tried to change ulimits without success.
16Go memory, 3Go free, 3Go used, 9Go buff/cache according to top.

**Comment by yokotsumo** [comment]
Just a memory issue. Cleared memory and it worked fine

**Comment by tongzou** [comment]
How did you clear the memory?

**Comment by yokotsumo** [comment]
I do not remember, sorry.
