### ISSUE TITLE
Ports blocked

### ISSUE THREAD

**Issue by FreeGoldRush** [UnusualAlpha/ib-gateway-docker#31]
Can't connect to ports 5900, 4001 or 4002.  Ports show as "filtered" in nmap.  ufw not fixing the issue.

Ubuntu 20.01 running in VirtualBox on a Windows 10 machine.  Opened ports with ufw but they are still blocked as nmap shows.  Any ideas on what I need to do?

(base) mike@wayne:~/ib-gateway-docker$ sudo ufw allow from any to any port 5900 proto tcp
Skipping adding existing rule
Skipping adding existing rule (v6)
(base) mike@wayne:~/ib-gateway-docker$ sudo nmap 192.168.0.162
Starting Nmap 7.80 ( https://nmap.org ) at 2022-10-22 13:08 EDT
Nmap scan report for wayne (192.168.0.162)
Host is up (0.0000040s latency).
Not shown: 993 closed ports
PORT     STATE    SERVICE
21/tcp   open     ftp
22/tcp   open     ssh
111/tcp  open     rpcbind
4001/tcp filtered newoak
4002/tcp filtered mlchat-proxy
5000/tcp open     upnp
5900/tcp filtered vnc

Nmap done: 1 IP address (1 host up) scanned in 1.40 seconds

**Comment by efernandesng** [comment]
Hi @FreeGoldRush!

How you run the docker image?
