### ISSUE TITLE
Cannot find run.sh

### ISSUE THREAD

**Issue by rcardinaux** [UnusualAlpha/ib-gateway-docker#35]
Hi there,

I am getting this error when running `docker-compose up`:

![image](https://user-images.githubusercontent.com/49291917/198848109-19af96fb-f2c0-469a-8bff-6813c2ba021f.png)

My `docker-compose.yml` contains what is shown in the ReadMe.

Any ideas what might be the issue?

**Comment by efernandesng** [comment]
Hi @rcardinaux 👋

Thank you for your report.

I tried it locally and it looks to work fine.

Can you share the output of the command `docker images ghcr.io/unusualalpha/ib-gateway --digests`?

**Comment by rcardinaux** [comment]
Hi @efernandesng,

Thanks for getting back to me that quickly.

There it is:
![image](https://user-images.githubusercontent.com/49291917/198878333-62d01650-33ab-4d30-a49b-773c1f94890f.png)

**Comment by efernandesng** [comment]
The column `DIGEST` shouldn't be `<none>`. Maybe it is related to [this](https://github.com/docker/cli/issues/728).

You can try to remove the `ghcr.io/unusualalpha/ib-gateway:latest` docker image in your local system to force a new image download. You can use the docker desktop or the command `docker image rm ghcr.io/unusualalpha/ib-gateway:latest`.

Let me know if it solves the problem.

**Comment by rcardinaux** [comment]
I tried removing the container and image and starting all over again, and now got that:

> PS C:\Users\rapha\Documents\Github\ib-gateway-docker> docker-compose up
> Creating network "ib-gateway-docker_default" with the default driver
> Pulling ib-gateway (ghcr.io/unusualalpha/ib-gateway:latest)...
> ERROR: Head "https://ghcr.io/v2/unusualalpha/ib-gateway/manifests/latest": denied: denied

Then I tried on my second machine, and it worked at first try.... Something is up with my main machine, but I don't know why. It's out of the scope of this project, so I will close this issue in 1-2 days unless someone feels sharing inputs by then.
